apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: curl
  namespace: default
  labels:
    app: curl
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: curl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
      version: v1
  template:
    metadata:
      labels:
        app: curl
        version: v1
    spec:
      serviceAccountName: curl
      containers:
      - image: curlimages/curl
        imagePullPolicy: IfNotPresent
        name: curl
        command: [ "sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
