apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
        managed-by: apigee
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
        - name: apigee-remote-service-envoy
          image: "google/apigee-envoy-adapter:v2.1.1"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5001
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5001
            failureThreshold: 30
            periodSeconds: 10
          args:
            - --log-level=debug
            - --config=/config/config.yaml
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 100Mi
          volumeMounts:
            - mountPath: /config
              name: apigee-remote-service-envoy
              readOnly: true
            - mountPath: /policy-secret
              name: policy-secret
              readOnly: true
      volumes:
        - name: apigee-remote-service-envoy
          configMap:
            name: apigee-remote-service-envoy
        - name: policy-secret
          secret:
            defaultMode: 420
            secretName: hc-73259e37dc554e4a9bac892ae3b-env-policy-secret
