apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: curl-to-httpbin
  namespace: default
spec:
  destination:
    name: httpbin
  sources:
  - name: curl
    action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: httpbin-to-proxy
  namespace: default
spec:
  destination:
    name: apigee-remote-service-envoy
    namespace: apigee
  sources:
  - name: httpbin
    action: allow
