apiVersion: v1
kind: Service
metadata:
  name: apigee-remote-service-envoy
  namespace: default
  labels:
    app: apigee-remote-service-envoy
    org: ${ORG}
    env: ${ENV}
spec:
  ports:
    - port: 5000
      name: grpc
  selector:
    app: apigee-remote-service-envoy
